# NMF
Bir LEGO şatosunu düşünün; farklı renklerde LEGO tuğlaları kullanarak yapılmış. Ancak bu şatoyu sadece birkaç belirli LEGO parçası kullanarak tanımlamanız gerekiyor.

Büyük LEGO Şatosu (V):
Bu, sahip olduğunuz ana veri kümesini temsil eder, örneğin bir sitedeki tüm film derecelendirmeleri. Her bir tuğla, bir kullanıcının belirli bir filme verdiği spesifik derecelendirmeyi temsil eder.

Belli Başlı LEGO Parçaları (W ve H):
Şatoyu iki daha küçük parça kümesine ayırıyorsunuz.
Bir küme (W), kullanıcıları ve genel kategorilere (aksiyon severler, romantik film severler vb.) nasıl uyduklarını temsil eder.
Diğer küme (H), her filmin bu genel kategorilere ne kadar uyduğunu temsil eder.

Bunu bir araya getirmek:
Bu iki parça kümesini kullanarak şatoyu yeniden inşa etmeye çalıştığınızda (W ve H'yı birleştirerek), orijinaliyle tam olarak aynı olmayacaktır. Ancak NMF'nin amacı, onu orijinaline olabildiğince yakın yapmaktır.
Yeniden inşa edilen şato orijinaline ne kadar yakınsa, kategorilerimiz o kadar iyidir ve kullanıcıları ve filmleri sadece bu kategorileri kullanarak daha doğru bir şekilde tanımlayabiliriz.

Eğer k çok küçükse, önemli detayları kaçırabilirsiniz (LEGO yapınızı sadece bir renkle yeniden inşa etmeye çalışmak gibi).
Eğer k çok büyükse, veriyi yeterince basitleştiremezsiniz (belki de yeterli olabilecek 10 renk yerine tüm 100 renği kullanmak gibi).
Yakınlık olarak resolution yükseltme ve düşürme gibi düşünülebilir.

In [84]:
# Gradient Descent'li olan versiyon
import numpy as np

# tol= Gradient Descent toleransi
# max_iter bir damping factor, runtime optimizasyonu
# Denemelerimde gradient error tolerantin en iyi 0,0000001 oldugunu fark ettim, 10000 iter icin
def nmf(V, k, max_iter=100000, tol=1e-7):
    m, n = V.shape

    # Random matrisler tanımla, boyutları k=resolutıon boyutlarını alsın)
    W = np.random.rand(m, k)
    H = np.random.rand(k, n)

    for iter in range(max_iter):

        # update rules
        # https://en.wikipedia.org/wiki/Non-negative_matrix_factorization#:~:text=There%20are%20several,to%20be%20useful.
        WH = np.dot(W, H)
        W *= np.dot(V, H.T) / np.dot(WH, H.T)
        H *= np.dot(W.T, V) / np.dot(W.T, WH)

        # Frobenius norm, gradient descent
        error = np.linalg.norm(V - np.dot(W, H))
        if error < tol:
            break

    return W, H


# Test
V = np.array([[5, 4, 0, 2],
              [4, 3, 0, 1],
              [3, 2, 4, 5],
              [2, 1, 5, 4]])

W, H = nmf(V, 2)
print("W:")
print(W)
print("\nH:")
print(H)
print("\nReconstructed V (WxH):")
print(np.dot(W, H))
print("\nOriginal matrix (V):")
print(V)

W:
[[7.31233620e-001 1.15836212e-002]
 [5.57781477e-001 4.94065646e-324]
 [3.68829049e-001 4.46631045e-001]
 [1.79304560e-001 4.80988447e-001]]

H:
[[9.62904921e-001 7.56463522e-001 1.97626258e-323 3.35218601e-001]
 [1.82799906e-001 3.61092489e-003 1.35431745e+000 1.14889681e+000]]

Reconstructed V (WxH):
[[7.06225936e-001 5.53193387e-001 1.56879004e-002 2.58431497e-001]
 [5.37090529e-001 4.21941340e-001 1.48219694e-323 1.86978727e-001]
 [4.36791420e-001 2.80618472e-001 6.04880219e-001 6.36771341e-001]
 [2.60577886e-001 1.37374172e-001 6.51411048e-001 6.12712315e-001]]

Original matrix (V):
[[5 4 0 2]
 [4 3 0 1]
 [3 2 4 5]
 [2 1 5 4]]
